version: "3.8"

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "6432:5432"
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - ${REDIS_PORT}:6379
  backend:
    build:
      context: src/backend
      target: dev
    container_name: backend
    env_file:
      - .env
    ports:
      - ${API_PORT}:8080
      - "2345:2345"
    volumes:
      - ./src/backend/:/app/
    links:
      - db
      - redis
  frontend:
    build:
      context: src/frontend
    container_name: frontend
    ports:
      - ${UI_PORT}:3000
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${BASE_URL}