version: "3.8"

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "6432:5432"
  backend:
    build:
      context: src/backend
      target: dev
    container_name: backend
    env_file:
      - .env
    ports:
      - ${API_PORT}:8080
      - "2345:2345"
    volumes:
      - ./src/backend:/app/backand
    links:
      - db
  frontend:
    build:
      context: src/frontend
      target: dev
    container_name: frontend
    ports:
      - ${UI_PORT}:3000
    volumes:
      - ./src/frontend:/app/frontend
      - ./src/frontend:/app/frontend/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true