version: "3.8"

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: src/backend
    restart: always
    container_name: backend
    env_file:
      - .env
    ports:
      - ${API_PORT}:8080
    links:
      - db
  frontend:
    build:
      context: src/frontend
    container_name: frontend
    ports:
      - ${UI_PORT}:3000
    volumes:
      - ./src/frontend:/app/frontend
      - ./src/frontend:/app/frontend/node_modules
    env_file:
      - .env
volumes:
  postgres_data:
