version: "3.8"

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
  backend:
    image: ghcr.io/stas12312/wishlists/backend:release
    restart: always
    env_file:
      - .env
    ports:
      - ${API_PORT}:8080
    links:
      - db
      - redis
  frontend:
    image: ghcr.io/stas12312/wishlists/ui:release
    ports:
      - ${UI_PORT}:3000
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${BASE_URL}
volumes:
  postgres_data:
  redis_data:
