version: "3.8"

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "6432:5432"
  backend:
    build:
      context: src/backend
      target: dev
    container_name: backend
    env_file:
      - .env
    ports:
      - ${API_PORT}:8080
      - "2345:2345"
    volumes:
      - ./src/backend:/app/backand
    links:
      - db