// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "main/model"

	mock "github.com/stretchr/testify/mock"
)

// WishRepository is an autogenerated mock type for the WishRepository type
type WishRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: wish
func (_m *WishRepository) Create(wish *model.Wish) (*model.Wish, error) {
	ret := _m.Called(wish)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Wish
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Wish) (*model.Wish, error)); ok {
		return rf(wish)
	}
	if rf, ok := ret.Get(0).(func(*model.Wish) *model.Wish); ok {
		r0 = rf(wish)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wish)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Wish) error); ok {
		r1 = rf(wish)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: wishUuid
func (_m *WishRepository) Delete(wishUuid string) error {
	ret := _m.Called(wishUuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(wishUuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: wishUuid
func (_m *WishRepository) Get(wishUuid string) (*model.Wish, error) {
	ret := _m.Called(wishUuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Wish
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.Wish, error)); ok {
		return rf(wishUuid)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Wish); ok {
		r0 = rf(wishUuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wish)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(wishUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBy provides a mock function with given fields: wishlistUuid, wishUUIDs
func (_m *WishRepository) ListBy(wishlistUuid string, wishUUIDs []string) (*[]model.Wish, error) {
	ret := _m.Called(wishlistUuid, wishUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListBy")
	}

	var r0 *[]model.Wish
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string) (*[]model.Wish, error)); ok {
		return rf(wishlistUuid, wishUUIDs)
	}
	if rf, ok := ret.Get(0).(func(string, []string) *[]model.Wish); ok {
		r0 = rf(wishlistUuid, wishUUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Wish)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(wishlistUuid, wishUUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReservedList provides a mock function with given fields: userId
func (_m *WishRepository) ReservedList(userId int64) (*[]model.Wish, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for ReservedList")
	}

	var r0 *[]model.Wish
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*[]model.Wish, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int64) *[]model.Wish); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Wish)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: wishUuid
func (_m *WishRepository) Restore(wishUuid string) error {
	ret := _m.Called(wishUuid)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(wishUuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetFulfilledAt provides a mock function with given fields: wishUuid, fulfilledAt
func (_m *WishRepository) SetFulfilledAt(wishUuid string, fulfilledAt model.NullTime) error {
	ret := _m.Called(wishUuid, fulfilledAt)

	if len(ret) == 0 {
		panic("no return value specified for SetFulfilledAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, model.NullTime) error); ok {
		r0 = rf(wishUuid, fulfilledAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPresenter provides a mock function with given fields: wishUuid, presenterId
func (_m *WishRepository) SetPresenter(wishUuid string, presenterId model.NullInt64) error {
	ret := _m.Called(wishUuid, presenterId)

	if len(ret) == 0 {
		panic("no return value specified for SetPresenter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, model.NullInt64) error); ok {
		r0 = rf(wishUuid, presenterId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: wish
func (_m *WishRepository) Update(wish *model.Wish) (*model.Wish, error) {
	ret := _m.Called(wish)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Wish
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Wish) (*model.Wish, error)); ok {
		return rf(wish)
	}
	if rf, ok := ret.Get(0).(func(*model.Wish) *model.Wish); ok {
		r0 = rf(wish)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wish)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Wish) error); ok {
		r1 = rf(wish)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWishRepository creates a new instance of WishRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWishRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WishRepository {
	mock := &WishRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
