// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	model "main/model"

	mock "github.com/stretchr/testify/mock"
)

// WishlistRepository is an autogenerated mock type for the WishlistRepository type
type WishlistRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: wishlist
func (_m *WishlistRepository) Create(wishlist *model.Wishlist) (*model.Wishlist, error) {
	ret := _m.Called(wishlist)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Wishlist
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Wishlist) (*model.Wishlist, error)); ok {
		return rf(wishlist)
	}
	if rf, ok := ret.Get(0).(func(*model.Wishlist) *model.Wishlist); ok {
		r0 = rf(wishlist)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wishlist)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Wishlist) error); ok {
		r1 = rf(wishlist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUUID provides a mock function with given fields: uuid
func (_m *WishlistRepository) GetByUUID(uuid string) (*model.Wishlist, error) {
	ret := _m.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Wishlist
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.Wishlist, error)); ok {
		return rf(uuid)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Wishlist); ok {
		r0 = rf(uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wishlist)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUserId provides a mock function with given fields: userId
func (_m *WishlistRepository) ListByUserId(userId int64) ([]model.Wishlist, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserId")
	}

	var r0 []model.Wishlist
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]model.Wishlist, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int64) []model.Wishlist); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Wishlist)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: wishlist
func (_m *WishlistRepository) Update(wishlist *model.Wishlist) (*model.Wishlist, error) {
	ret := _m.Called(wishlist)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Wishlist
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Wishlist) (*model.Wishlist, error)); ok {
		return rf(wishlist)
	}
	if rf, ok := ret.Get(0).(func(*model.Wishlist) *model.Wishlist); ok {
		r0 = rf(wishlist)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wishlist)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Wishlist) error); ok {
		r1 = rf(wishlist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWishlistRepository creates a new instance of WishlistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWishlistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WishlistRepository {
	mock := &WishlistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
