name: EsLint

on:
  pull_request:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            frontend:
              - 'src/frontend/**'
      - name: Check eslint
        if: steps.changes.outputs.frontend == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
        if: steps.changes.outputs.frontend == 'true'
      - run: npm run lint
        if: steps.changes.outputs.frontend == 'true'
