name: EsLint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend
    steps:
      - uses: actions/checkout@v4
      - name: Check eslint
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run lint
