name: Go tests

on:
  pull_request:
    branches:
      - main

jobs:

  go-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'src/backend/**'
      - name: Set up Go
        if: steps.changes.outputs.backend == 'true'
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
          cache-dependency-path: src/backend/go.sum

      - name: Install dependencies
        if: steps.changes.outputs.backend == 'true'
        run: go get .

      - name: Build
        if: steps.changes.outputs.backend == 'true'
        run: go build -v ./...

      - name: Test
        if: steps.changes.outputs.backend == 'true'
        run: go test -json -v ./... -json > TestResults.json

      - name: Upload Go test results
        if: steps.changes.outputs.backend == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Go-results
          path: ./src/backend/TestResults.json
          if-no-files-found: error