name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
          cache-dependency-path: src/backend/go.sum

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -json -v ./... -json > TestResults.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results
          path: ./src/backend/TestResults.json
          if-no-files-found: error