name: release-deploy

on:
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend
        uses: docker/build-push-action@v6
        with:
          context: ./wishlists/src/backend
          file: ./wishlists/src/backend/Dockerfile
          push: true
          tags: wishlists/backend:release

      - name: Build UI
        uses: docker/build-push-action@v6
        with:
          context: ./wishlists/src/frontend
          file: ./wishlists/src/frontend/Dockerfile
          push: true
          tags: wishlists/ui:release